trigger: none

pool:
  name: self-hosted-local


 
stages:
  - stage: CI
    displayName: CI Stage
    jobs:
      - job: Lint
        displayName: Linting Backend
        steps:
          - checkout: self
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
              addToPath: true    # Prepends the retrieved Python version to the PATH environment variable to make it available in subsequent tasks or scripts without using the output variable.
          - script: |
              sudo  rm -rf .venv
              python3.9 -m venv .venv
              source .venv/bin/activate
              python3.9 get-pip.py 
              pip install pylint flake8 black isort 
              pylint src/feedback_backend/app.py           # Lint with Pylint (checks for code quality and style issues (rates the code out of 10))
              flake8 src/feedback_backend/app.py           # Check PEP 8 and complexity with Flake8 (Ensures code follows Python style guide)
              black src/feedback_backend/app.py            # Auto-format code with Black and isort 
              isort src/feedback_backend/app.py
            displayName: "Run Linting"  
            workingDirectory: $(Build.SourcesDirectory)
            
      - job: Test
        dependsOn: Lint
        displayName: unit test backend
        steps:
          - checkout: self
          - script: |
              python3.9 -m venv .venv
              source .venv/bin/activate
              pip install -r src/feedback_backend/requirements.txt
              pip install pytest flask-testing
              pytest
            displayName: run unit tests  
            workingDirectory: $(Build.SourcesDirectory)            
