trigger:
- main

pool:
  name: self-hosted

variables:
  - group: AWS Credential

stages:
- stage: Plan_and_deploy
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - script: |
        export  AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
        export  AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
        export  AWS_SESSION_TOKEN=$(AWS_SESSION_TOKEN)
        terraform init
        terraform plan
      displayName: 'Terraform Init and Plan'
      workingDirectory: "infra"

  - job: Terraformdeploy
    displayName: 'Terraform Deploy'
    steps:
      - checkout: self
      - task: TerraformInstaller@0
      - script: |
          export  AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
          export  AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
          export  AWS_SESSION_TOKEN=$(AWS_SESSION_TOKEN)
          terraform apply --auto-approve
        workingDirectory: "infra"  




