trigger:
- main

pool:
  name: self-hosted-local

stages:

- stage: configure_agent
  displayName: configure the agent using ansible
  jobs:
    - job: configure_agent
      displayName: configure the agent using ansible
      steps:
        - checkout: self
        - script: |
            sudo apt update
            sudo apt install ansible -y 
        - task: Ansible@0
          inputs:
            ansibleInterface: 'agentMachine'
            playbookPathOnAgentMachine: 'feedback_app_infra/ansible/conf.yml'
            inventoriesAgentMachine: 'file'
            inventoryFileOnAgentMachine: 'feedback_app_infra/ansible/inventory.ini'
