trigger: none

pool:
  name: self-hosted-local

variables:
  - group: "AWS Credential"

stages:
  - stage: init_destroy_infra
    displayName: init and destroy stage
    jobs:
      - job:  init_destroy_infra
        displayName: init and destroy
        steps:
          - checkout: self
      
          - script: |
              export aws_access_key_id=$(aws_access_key_id)
              export aws_secret_access_key=$(aws_secret_access_key)
              export aws_session_token=$(aws_session_token)

          - task: TerraformInstaller@2
            displayName: installing latest terraform version
            inputs:
              terraformVersion: 'latest'
           
           
          - task: TerraformCLI@2
            displayName: terraform init
            inputs:
              command: 'init'
              workingDirectory: 'feedback_app_infra/terraform'
              allowTelemetryCollection: false

          - task: TerraformCLI@2
            displayName: terraform destroy
            inputs:
              command: 'destroy'
              workingDirectory: 'feedback_app_infra/terraform'
              allowTelemetryCollection: false    

