apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name.frontend }}
  labels:
     {{- include "ahmed-FeedbackApp-HelmChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name.frontend }}
  template:
    metadata:
      labels:
        app: {{ .Values.name.frontend }}
    spec:
      containers:
      - name: {{ .Values.name.frontend }}
        image: {{ .Values.image.frontend }}:{{ .Chart.AppVersion }}
        ports:
        - containerPort: {{ .Values.containerPort.frontend }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.frontend.name }}
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: {{ .Values.name.frontend }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      nodePort: {{ .Values.service.frontend.nodePort }}
